/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClassDto } from '../../models/class-dto';

export interface GetChartAccountsByCategory$Params {
  classId: string;
}

export function getChartAccountsByCategory(http: HttpClient, rootUrl: string, params: GetChartAccountsByCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: ClassDto;
}>> {
  const rb = new RequestBuilder(rootUrl, getChartAccountsByCategory.PATH, 'get');
  if (params) {
    rb.query('classId', params.classId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: ClassDto;
      }>;
    })
  );
}

getChartAccountsByCategory.PATH = '/api/v1/chart-account/categories';
