name: 'is'
version: '3.8'


services:
  db:
    image: postgres:latest
    container_name: database_is
    environment:
      POSTGRES_USER: invoicesync_db_user
      POSTGRES_PASSWORD: invoicesync_db_password
      POSTGRES_DB: invoicesync_db
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    container_name: backend_is
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      POSTGRES_USER: invoicesync_db_user
      POSTGRES_PASSWORD: invoicesync_db_password
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/invoicesync_db
      SPRING_DATASOURCE_USERNAME: invoicesync_db_user
      SPRING_DATASOURCE_PASSWORD: invoicesync_db_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge