ALTER TABLE invoice_sync.invoice RENAME COLUMN invoice_import_date TO import_date;
ALTER TABLE invoice_sync.invoice RENAME COLUMN invoice_issue_date TO issue_date;
ALTER TABLE invoice_sync.invoice RENAME COLUMN invoice_delivery_date TO delivery_date;
ALTER TABLE invoice_sync.invoice RENAME COLUMN invoice_due_date TO due_date;
ALTER TABLE invoice_sync.invoice RENAME COLUMN invoice_variable_symbol TO variable_symbol;
ALTER TABLE invoice_sync.invoice RENAME COLUMN invoice_company_name TO partner_name;
ALTER TABLE invoice_sync.invoice RENAME COLUMN invoice_company_city TO partner_city;
ALTER TABLE invoice_sync.invoice RENAME COLUMN invoice_company_address TO partner_street;
ALTER TABLE invoice_sync.invoice RENAME COLUMN invoice_company_zip TO partner_zip;
ALTER TABLE invoice_sync.invoice RENAME COLUMN invoice_company_vat_number TO partner_vat_id;
ALTER TABLE invoice_sync.invoice RENAME COLUMN invoice_company_registration_number TO partner_registration_number;
ALTER TABLE invoice_sync.invoice RENAME COLUMN invoice_tax_number TO partner_tax_id;
ALTER TABLE invoice_sync.invoice DROP COLUMN status;
ALTER TABLE invoice_sync.invoice RENAME COLUMN invoice_status TO status;
ALTER TABLE invoice_sync.invoice DROP COLUMN invoice_company_iban;
ALTER TABLE invoice_sync.invoice DROP COLUMN invoice_total_amount;
ALTER TABLE invoice_sync.invoice DROP COLUMN delivery_date;
ALTER TABLE invoice_sync.invoice ADD COLUMN accounting_date varchar;
ALTER TABLE invoice_sync.invoice ADD COLUMN tax_date varchar;