package com.invoicesync.modules.invoice.pohoda;

import java.io.ByteArrayOutputStream;

import javax.xml.transform.dom.DOMResult;

import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.JAXBException;
import jakarta.xml.bind.Marshaller;

import org.springframework.stereotype.Service;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

import com.invoicesync.integration.pohoda.generated.datapack.DataPackItemType;
import com.invoicesync.integration.pohoda.generated.datapack.DataPackType;
import com.invoicesync.integration.pohoda.generated.datapack.ObjectFactory;
import com.invoicesync.integration.pohoda.generated.invoice.InvoiceType;

@Service
public class PohodaXmlBuilder {

  public byte[] buildInvoiceXml(final InvoiceType invoiceType, final String registrationNumber,
      final String invoiceNumber) throws JAXBException {

    JAXBContext invoiceContext =
        JAXBContext.newInstance(com.invoicesync.integration.pohoda.generated.invoice.InvoiceType.class);
    Marshaller invoiceMarshaller = invoiceContext.createMarshaller();

    DOMResult domResult = new DOMResult();
    invoiceMarshaller.marshal(
        new com.invoicesync.integration.pohoda.generated.invoice.ObjectFactory().createInvoice(invoiceType),
        domResult);
    Element invoiceElement = ((Document) domResult.getNode()).getDocumentElement();

    DataPackItemType dataPackItemType = new DataPackItemType();
    dataPackItemType.setId("1");
    dataPackItemType.setVersion("2.0");
    dataPackItemType.setAny(invoiceElement);

    DataPackType dataPackType = new DataPackType();
    dataPackType.setId("1");
    dataPackType.setIco(registrationNumber);
    dataPackType.setApplication("InvoiceSync");
    dataPackType.setNote("Generated by InvoiceSync" + invoiceNumber);
    dataPackType.setVersion("2.0");
    dataPackType.getDataPackItem().add(dataPackItemType);

    ObjectFactory objectFactory = new ObjectFactory();
    JAXBContext dataPackContext = JAXBContext.newInstance(DataPackType.class);
    Marshaller dataPackMarshaller = dataPackContext.createMarshaller();
    dataPackMarshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);

    ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    dataPackMarshaller.marshal(objectFactory.createDataPack(dataPackType), outputStream);

    return outputStream.toByteArray();
  }

}
