/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountDto } from '../models/account-dto';
export interface CategoryDto {
  accounts?: Array<AccountDto>;
  categoryName?: string;
}
