/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyResponseDto {
  city?: string;
  id?: number;
  name?: string;
  registrationNumber?: string;
  street?: string;
  streetNumber?: string;
  taxId?: string;
  vatId?: string;
  zip?: string;
}
