/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyRequest {
  name: string;
  city: string;
  id?: number;
  registrationNumber: string;
  street: string;
  streetNumber: string;
  taxId: string;
  vatId: string;
  zip: string;
}
