/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InvoiceItemDto } from '../models/invoice-item-dto';
import { InvoiceRequestDetailsDto } from '../models/invoice-request-details-dto';
import { MyIdentityDto } from '../models/my-identity-dto';
import { Partner } from './partner';
export interface InvoiceRequestDto {
  invoiceDetails?: InvoiceRequestDetailsDto;
  items?: Array<InvoiceItemDto>;
  myIdentity?: MyIdentityDto;
  partner?: Partner;
}
