/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvoiceItemDto {
  accountValue?: string;
  price?: number;
  priceSum?: number;
  priceVAT?: number;
  quantity?: number;
  unitPrice?: number;
}
