/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MyIdentityDto {
  city?: string;
  name?: string;
  registrationNumber?: string;
  street?: string;
  streetNumber?: string;
  surname?: string;
  taxId?: string;
  vatId?: string;
  zip?: string;
}
