/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyResponseDto } from '../models/company-response-dto';
export interface PageResponseCompanyResponseDto {
  content: Array<CompanyResponseDto>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
