/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Partner {
  city?: string;
  name?: string;
  registrationNumber?: string;
  street?: string;
  taxId?: string;
  vatId?: string;
  zip?: string;
}
