/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Partner } from './partner';
import { ReceiptItem } from './receipt-item';
import { ReceiptResponseDetailsDto } from '../models/receipt-response-details-dto';
export interface ReceiptDetailsDto {
  company?: number;
  id?: number;
  items?: Array<ReceiptItem>;
  partner?: Partner;
  receiptDetails?: ReceiptResponseDetailsDto;
}
