/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReceiptListDto {
  company?: string;
  id?: number;
  importDate?: string;
  partnerName?: string;
  partnerRegistrationNumber?: string;
  partnerTaxId?: string;
  partnerVatId?: string;
  totalPrice?: string;
}
