/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReceiptItem {
  accountText?: string;
  name?: string;
  quantity?: number;
  priceWithoutVAT?: number;
  vatRate?: number;
  priceWithVAT?: number;
  accountValue?: string;
  id?: number;
}
