/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReceiptResponseDetailsDto {
  accountValue?: string;
  classificationKVVAT?: string;
  classificationVAT?: string;
  date?: string;
  datePayment?: string;
  dateTax?: string;
  description?: string;
  totalPrice?: string;
}
