/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Company {
  city?: string;
  id: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  name?: string;
  registrationNumber?: string;
  street?: string;
  streetNumber?: string;
  taxId?: string;
  vatId?: string;
  zip?: string;
}
