/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvoiceRequestDetailsDto {
  dateAccounting?: string;
  dateDue?: string;
  dateIssue?: string;
  dateTax?: string;
  invoiceNumber?: string;
  invoiceType?: string;
  pairingSymbol?: string;
  variableSymbol?: string;
}
