/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDemo } from './user-demo';
export interface PostingAccount {
  accountId?: string;
  accountName?: string;
  category?: string;
  categoryName?: string;
  classId?: string;
  className?: string;
  editable?: boolean;
  id?: number;
  user?: UserDemo;
}
