/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MyIdentityDto } from './my-identity-dto';
import { Partner } from './partner';
import { ReceiptItem } from './receipt-item';
import { ReceiptRequestDetailsDto } from './receipt-request-details-dto';
export interface ReceiptRequestDto {
  items?: Array<ReceiptItem>;
  myIdentity?: MyIdentityDto;
  partner?: Partner;
  receiptDetails?: ReceiptRequestDetailsDto;
}
