/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReceiptItem {
  id?: number;
  name?: string;
  quantity?: number;
  unitType?: string;
  vatRate?: number;
  unitPriceWithoutVat?: number;
  unitPriceWithVat?: number;
  totalItemPriceWithVat?: number;
  accountValue?: string;
  accountText?: string;
}
