/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChartAccount } from './chart-account';
import { Company } from './company';
import { GrantedAuthority } from './granted-authority';
import { Token } from './token';
import { XmlFile } from './xml-file';
export interface UserDemo {
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  chartAccounts?: Array<ChartAccount>;
  companies?: Array<Company>;
  credentialsNonExpired?: boolean;
  enabled?: boolean;
  id?: number;
  login?: string;
  mfa_enabled?: boolean;
  name?: string;
  password?: string;
  role?: 'USER' | 'ADMIN';
  secret?: string;
  tokens?: Array<Token>;
  username?: string;
  xmlFiles?: Array<XmlFile>;
}
