/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDemo } from './user-demo';
export interface XmlFile {
  created_at?: string;
  file_name?: string;
  id?: number;
  user?: UserDemo;
  xml_content?: string;
}
