/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RunPythonScript$Params {
  username: string;
  filePath: string;
  schemaPath: string;
}

export function runPythonScript(http: HttpClient, rootUrl: string, params: RunPythonScript$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, runPythonScript.PATH, 'get');
  if (params) {
    rb.query('username', params.username, {});
    rb.query('filePath', params.filePath, {});
    rb.query('schemaPath', params.schemaPath, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

runPythonScript.PATH = '/runPythonScript';
