/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ClassDto } from '../models/class-dto';
import { getChartAccountsByCategory } from '../fn/chart-account-controller/get-chart-accounts-by-category';
import { GetChartAccountsByCategory$Params } from '../fn/chart-account-controller/get-chart-accounts-by-category';

@Injectable({ providedIn: 'root' })
export class ChartAccountControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getChartAccountsByCategory()` */
  static readonly GetChartAccountsByCategoryPath = '/api/v1/chart-account/categories';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getChartAccountsByCategory()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChartAccountsByCategory$Response(params: GetChartAccountsByCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: ClassDto;
}>> {
    return getChartAccountsByCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getChartAccountsByCategory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChartAccountsByCategory(params: GetChartAccountsByCategory$Params, context?: HttpContext): Observable<{
[key: string]: ClassDto;
}> {
    return this.getChartAccountsByCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: ClassDto;
}>): {
[key: string]: ClassDto;
} => r.body)
    );
  }

}
