/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Company } from '../models/company';
import { CompanyResponseDto } from '../models/company-response-dto';
import { deleteCompany } from '../fn/company-controller/delete-company';
import { DeleteCompany$Params } from '../fn/company-controller/delete-company';
import { editCompany } from '../fn/company-controller/edit-company';
import { EditCompany$Params } from '../fn/company-controller/edit-company';
import { findAllCompaniesByUser } from '../fn/company-controller/find-all-companies-by-user';
import { FindAllCompaniesByUser$Params } from '../fn/company-controller/find-all-companies-by-user';
import { getCompanyById } from '../fn/company-controller/get-company-by-id';
import { GetCompanyById$Params } from '../fn/company-controller/get-company-by-id';
import { PageResponseCompanyResponseDto } from '../models/page-response-company-response-dto';
import { saveCompany } from '../fn/company-controller/save-company';
import { SaveCompany$Params } from '../fn/company-controller/save-company';

@Injectable({ providedIn: 'root' })
export class CompanyControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `editCompany()` */
  static readonly EditCompanyPath = '/company/update/{companyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `editCompany()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  editCompany$Response(params: EditCompany$Params, context?: HttpContext): Observable<StrictHttpResponse<Company>> {
    return editCompany(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `editCompany$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  editCompany(params: EditCompany$Params, context?: HttpContext): Observable<Company> {
    return this.editCompany$Response(params, context).pipe(
      map((r: StrictHttpResponse<Company>): Company => r.body)
    );
  }

  /** Path part for operation `saveCompany()` */
  static readonly SaveCompanyPath = '/company/save';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveCompany()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveCompany$Response(params: SaveCompany$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveCompany(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveCompany$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveCompany(params: SaveCompany$Params, context?: HttpContext): Observable<number> {
    return this.saveCompany$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getCompanyById()` */
  static readonly GetCompanyByIdPath = '/company/{company-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCompanyById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCompanyById$Response(params: GetCompanyById$Params, context?: HttpContext): Observable<StrictHttpResponse<CompanyResponseDto>> {
    return getCompanyById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCompanyById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCompanyById(params: GetCompanyById$Params, context?: HttpContext): Observable<CompanyResponseDto> {
    return this.getCompanyById$Response(params, context).pipe(
      map((r: StrictHttpResponse<CompanyResponseDto>): CompanyResponseDto => r.body)
    );
  }

  /** Path part for operation `findAllCompaniesByUser()` */
  static readonly FindAllCompaniesByUserPath = '/company/user';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllCompaniesByUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllCompaniesByUser$Response(params?: FindAllCompaniesByUser$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseCompanyResponseDto>> {
    return findAllCompaniesByUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllCompaniesByUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllCompaniesByUser(params?: FindAllCompaniesByUser$Params, context?: HttpContext): Observable<PageResponseCompanyResponseDto> {
    return this.findAllCompaniesByUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseCompanyResponseDto>): PageResponseCompanyResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteCompany()` */
  static readonly DeleteCompanyPath = '/company/delete/{companyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteCompany()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCompany$Response(params: DeleteCompany$Params, context?: HttpContext): Observable<StrictHttpResponse<Company>> {
    return deleteCompany(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteCompany$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCompany(params: DeleteCompany$Params, context?: HttpContext): Observable<Company> {
    return this.deleteCompany$Response(params, context).pipe(
      map((r: StrictHttpResponse<Company>): Company => r.body)
    );
  }

}
