/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createInvoice } from '../fn/pohoda-controller/create-invoice';
import { CreateInvoice$Params } from '../fn/pohoda-controller/create-invoice';
import { createReceipt1 } from '../fn/pohoda-controller/create-receipt-1';
import { CreateReceipt1$Params } from '../fn/pohoda-controller/create-receipt-1';

@Injectable({ providedIn: 'root' })
export class PohodaControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createInvoice()` */
  static readonly CreateInvoicePath = '/api/v1/pohoda/export/received';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createInvoice()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createInvoice$Response(params: CreateInvoice$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return createInvoice(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createInvoice$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createInvoice(params: CreateInvoice$Params, context?: HttpContext): Observable<string> {
    return this.createInvoice$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `createReceipt1()` */
  static readonly CreateReceipt1Path = '/api/v1/pohoda/export/receipt';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createReceipt1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createReceipt1$Response(params: CreateReceipt1$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return createReceipt1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createReceipt1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createReceipt1(params: CreateReceipt1$Params, context?: HttpContext): Observable<string> {
    return this.createReceipt1$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
