/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { runPythonScript } from '../fn/python-controller/run-python-script';
import { RunPythonScript$Params } from '../fn/python-controller/run-python-script';

@Injectable({ providedIn: 'root' })
export class PythonControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `runPythonScript()` */
  static readonly RunPythonScriptPath = '/runPythonScript';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `runPythonScript()` instead.
   *
   * This method doesn't expect any request body.
   */
  runPythonScript$Response(params: RunPythonScript$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return runPythonScript(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `runPythonScript$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  runPythonScript(params: RunPythonScript$Params, context?: HttpContext): Observable<string> {
    return this.runPythonScript$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
