/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createReceipt } from '../fn/receipt-controller/create-receipt';
import { CreateReceipt$Params } from '../fn/receipt-controller/create-receipt';
import { getReceiptById } from '../fn/receipt-controller/get-receipt-by-id';
import { GetReceiptById$Params } from '../fn/receipt-controller/get-receipt-by-id';
import { getReceiptsByCompanyId } from '../fn/receipt-controller/get-receipts-by-company-id';
import { GetReceiptsByCompanyId$Params } from '../fn/receipt-controller/get-receipts-by-company-id';
import { getReceiptsCurrentUser } from '../fn/receipt-controller/get-receipts-current-user';
import { GetReceiptsCurrentUser$Params } from '../fn/receipt-controller/get-receipts-current-user';
import { ReceiptDetailsDto } from '../models/receipt-details-dto';
import { ReceiptListDto } from '../models/receipt-list-dto';
import { saveReceipt } from '../fn/receipt-controller/save-receipt';
import { SaveReceipt$Params } from '../fn/receipt-controller/save-receipt';
import { updateReceipt } from '../fn/receipt-controller/update-receipt';
import { UpdateReceipt$Params } from '../fn/receipt-controller/update-receipt';

@Injectable({ providedIn: 'root' })
export class ReceiptControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateReceipt()` */
  static readonly UpdateReceiptPath = '/api/v1/receipt/update/{receiptId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateReceipt()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateReceipt$Response(params: UpdateReceipt$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateReceipt(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateReceipt$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateReceipt(params: UpdateReceipt$Params, context?: HttpContext): Observable<void> {
    return this.updateReceipt$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `saveReceipt()` */
  static readonly SaveReceiptPath = '/api/v1/receipt/save';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveReceipt()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveReceipt$Response(params: SaveReceipt$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return saveReceipt(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveReceipt$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveReceipt(params: SaveReceipt$Params, context?: HttpContext): Observable<void> {
    return this.saveReceipt$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `createReceipt()` */
  static readonly CreateReceiptPath = '/api/v1/receipt/pohoda/export/receipt';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createReceipt()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createReceipt$Response(params: CreateReceipt$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return createReceipt(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createReceipt$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createReceipt(params: CreateReceipt$Params, context?: HttpContext): Observable<string> {
    return this.createReceipt$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getReceiptById()` */
  static readonly GetReceiptByIdPath = '/api/v1/receipt/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getReceiptById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReceiptById$Response(params: GetReceiptById$Params, context?: HttpContext): Observable<StrictHttpResponse<ReceiptDetailsDto>> {
    return getReceiptById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getReceiptById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReceiptById(params: GetReceiptById$Params, context?: HttpContext): Observable<ReceiptDetailsDto> {
    return this.getReceiptById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReceiptDetailsDto>): ReceiptDetailsDto => r.body)
    );
  }

  /** Path part for operation `getReceiptsCurrentUser()` */
  static readonly GetReceiptsCurrentUserPath = '/api/v1/receipt/current-user';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getReceiptsCurrentUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReceiptsCurrentUser$Response(params?: GetReceiptsCurrentUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReceiptListDto>>> {
    return getReceiptsCurrentUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getReceiptsCurrentUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReceiptsCurrentUser(params?: GetReceiptsCurrentUser$Params, context?: HttpContext): Observable<Array<ReceiptListDto>> {
    return this.getReceiptsCurrentUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ReceiptListDto>>): Array<ReceiptListDto> => r.body)
    );
  }

  /** Path part for operation `getReceiptsByCompanyId()` */
  static readonly GetReceiptsByCompanyIdPath = '/api/v1/receipt/company/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getReceiptsByCompanyId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReceiptsByCompanyId$Response(params: GetReceiptsByCompanyId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReceiptListDto>>> {
    return getReceiptsByCompanyId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getReceiptsByCompanyId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReceiptsByCompanyId(params: GetReceiptsByCompanyId$Params, context?: HttpContext): Observable<Array<ReceiptListDto>> {
    return this.getReceiptsByCompanyId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ReceiptListDto>>): Array<ReceiptListDto> => r.body)
    );
  }

}
