/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getCurrentUserXmlFiles } from '../fn/xml-file-controller/get-current-user-xml-files';
import { GetCurrentUserXmlFiles$Params } from '../fn/xml-file-controller/get-current-user-xml-files';
import { getXmlContentByImportId } from '../fn/xml-file-controller/get-xml-content-by-import-id';
import { GetXmlContentByImportId$Params } from '../fn/xml-file-controller/get-xml-content-by-import-id';
import { processAndGenerateZip } from '../fn/xml-file-controller/process-and-generate-zip';
import { ProcessAndGenerateZip$Params } from '../fn/xml-file-controller/process-and-generate-zip';
import { saveXmlFile } from '../fn/xml-file-controller/save-xml-file';
import { SaveXmlFile$Params } from '../fn/xml-file-controller/save-xml-file';
import { XmlFileResponseDto } from '../models/xml-file-response-dto';

@Injectable({ providedIn: 'root' })
export class XmlFileControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `saveXmlFile()` */
  static readonly SaveXmlFilePath = '/xml-file/upload';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveXmlFile()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveXmlFile$Response(params?: SaveXmlFile$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return saveXmlFile(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveXmlFile$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveXmlFile(params?: SaveXmlFile$Params, context?: HttpContext): Observable<Array<string>> {
    return this.saveXmlFile$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `processAndGenerateZip()` */
  static readonly ProcessAndGenerateZipPath = '/xml-file/generate-zip/{importId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `processAndGenerateZip()` instead.
   *
   * This method doesn't expect any request body.
   */
  processAndGenerateZip$Response(params: ProcessAndGenerateZip$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return processAndGenerateZip(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `processAndGenerateZip$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  processAndGenerateZip(params: ProcessAndGenerateZip$Params, context?: HttpContext): Observable<string> {
    return this.processAndGenerateZip$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getCurrentUserXmlFiles()` */
  static readonly GetCurrentUserXmlFilesPath = '/xml-file/imports/current-user';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCurrentUserXmlFiles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUserXmlFiles$Response(params?: GetCurrentUserXmlFiles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<XmlFileResponseDto>>> {
    return getCurrentUserXmlFiles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCurrentUserXmlFiles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUserXmlFiles(params?: GetCurrentUserXmlFiles$Params, context?: HttpContext): Observable<Array<XmlFileResponseDto>> {
    return this.getCurrentUserXmlFiles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<XmlFileResponseDto>>): Array<XmlFileResponseDto> => r.body)
    );
  }

  /** Path part for operation `getXmlContentByImportId()` */
  static readonly GetXmlContentByImportIdPath = '/xml-file/content/{importId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getXmlContentByImportId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getXmlContentByImportId$Response(params: GetXmlContentByImportId$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return getXmlContentByImportId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getXmlContentByImportId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getXmlContentByImportId(params: GetXmlContentByImportId$Params, context?: HttpContext): Observable<string> {
    return this.getXmlContentByImportId$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
