package com.invoicesync.modules.activity.model;

public enum UserActivityType {

  LOGGED_IN,
  LOGGED_OUT,
  PASSWORD_RESET,

  // Invoice
  BULK_INVOICE_DOWNLOAD,
  DOCUMENT_UPLOAD_INVOICE,
  DOCUMENT_DELETE_INVOICE,
  CREATED_INVOICE,

  // Receipt
  EXPORT_RECEIPT,
  DOCUMENT_UPLOAD_RECEIPT,
  DOCUMENT_DELETE_RECEIPT,
  DELETE_RECEIPT
}
