/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { XmlFileControllerService } from './services/xml-file-controller.service';
import { CompanyControllerService } from './services/company-controller.service';
import { ReceiptControllerService } from './services/receipt-controller.service';
import { PohodaControllerService } from './services/pohoda-controller.service';
import { PythonControllerService } from './services/python-controller.service';
import { MessageService } from './services/message.service';
import { DemoControllerService } from './services/demo-controller.service';
import { ChartAccountControllerService } from './services/chart-account-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    XmlFileControllerService,
    CompanyControllerService,
    ReceiptControllerService,
    PohodaControllerService,
    PythonControllerService,
    MessageService,
    DemoControllerService,
    ChartAccountControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
