/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AccountDto } from './models/account-dto';
export type { CategoryDto } from './models/category-dto';
export type { ChartAccount } from './models/chart-account';
export type { ClassDto } from './models/class-dto';
export type { Company } from './models/company';
export type { CompanyRequest } from './models/company-request';
export type { CompanyResponseDto } from './models/company-response-dto';
export type { GrantedAuthority } from './models/granted-authority';
export type { InvoiceItemDto } from './models/invoice-item-dto';
export type { InvoiceRequestDetailsDto } from './models/invoice-request-details-dto';
export type { InvoiceRequestDto } from './models/invoice-request-dto';
export type { MyIdentityDto } from './models/my-identity-dto';
export type { PageResponseCompanyResponseDto } from './models/page-response-company-response-dto';
export type { Partner } from './models/partner';
export type { ReceiptDetailsDto } from './models/receipt-details-dto';
export type { ReceiptItem } from './models/receipt-item';
export type { ReceiptListDto } from './models/receipt-list-dto';
export type { ReceiptRequestDetailsDto } from './models/receipt-request-details-dto';
export type { ReceiptRequestDto } from './models/receipt-request-dto';
export type { ReceiptResponseDetailsDto } from './models/receipt-response-details-dto';
export type { Token } from './models/token';
export type { UserDemo } from './models/user-demo';
export type { XmlFile } from './models/xml-file';
export type { XmlFileResponseDto } from './models/xml-file-response-dto';
