/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReceiptDetailsDto } from '../../models/receipt-details-dto';

export interface GetReceiptById$Params {
  id: number;
}

export function getReceiptById(http: HttpClient, rootUrl: string, params: GetReceiptById$Params, context?: HttpContext): Observable<StrictHttpResponse<ReceiptDetailsDto>> {
  const rb = new RequestBuilder(rootUrl, getReceiptById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReceiptDetailsDto>;
    })
  );
}

getReceiptById.PATH = '/api/v1/receipt/{id}';
