/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReceiptListDto } from '../../models/receipt-list-dto';

export interface GetReceiptsCurrentUser$Params {
}

export function getReceiptsCurrentUser(http: HttpClient, rootUrl: string, params?: GetReceiptsCurrentUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReceiptListDto>>> {
  const rb = new RequestBuilder(rootUrl, getReceiptsCurrentUser.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ReceiptListDto>>;
    })
  );
}

getReceiptsCurrentUser.PATH = '/api/v1/receipt/current-user';
