/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { XmlFileResponseDto } from '../../models/xml-file-response-dto';

export interface GetCurrentUserXmlFiles$Params {
}

export function getCurrentUserXmlFiles(http: HttpClient, rootUrl: string, params?: GetCurrentUserXmlFiles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<XmlFileResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, getCurrentUserXmlFiles.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<XmlFileResponseDto>>;
    })
  );
}

getCurrentUserXmlFiles.PATH = '/xml-file/imports/current-user';
