/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseCompanyResponseDto } from '../../models/page-response-company-response-dto';

export interface FindAllCompaniesByUser$Params {
  page?: number;
  size?: number;
}

export function findAllCompaniesByUser(http: HttpClient, rootUrl: string, params?: FindAllCompaniesByUser$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseCompanyResponseDto>> {
  const rb = new RequestBuilder(rootUrl, findAllCompaniesByUser.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseCompanyResponseDto>;
    })
  );
}

findAllCompaniesByUser.PATH = '/company/user';
