/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyResponseDto } from '../../models/company-response-dto';

export interface GetCompanyById$Params {
  'company-id': number;
}

export function getCompanyById(http: HttpClient, rootUrl: string, params: GetCompanyById$Params, context?: HttpContext): Observable<StrictHttpResponse<CompanyResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getCompanyById.PATH, 'get');
  if (params) {
    rb.path('company-id', params['company-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompanyResponseDto>;
    })
  );
}

getCompanyById.PATH = '/company/{company-id}';
